### ISSUE TITLE
Render issueds

### ISSUE THREAD

**Issue by ihaveacrushonjaidenanimations2068** [MrCrayfish/MrCrayfishVehicleMod#100]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 2/25/19 9:30 PM
Description: Rendering Block Entity

java.lang.ArrayIndexOutOfBoundsException: 37
	at com.mrcrayfish.vehicle.client.render.AbstractRenderVehicle.renderDamagedPart(AbstractRenderVehicle.java:115)
	at com.mrcrayfish.vehicle.client.render.AbstractRenderVehicle.renderDamagedPart(AbstractRenderVehicle.java:102)
	at com.mrcrayfish.vehicle.client.render.AbstractRenderVehicle.renderDamagedPart(AbstractRenderVehicle.java:96)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderMoped.render(RenderMoped.java:40)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderMoped.render(RenderMoped.java:19)
	at com.mrcrayfish.vehicle.client.render.RenderMotorcycleWrapper.render(RenderMotorcycleWrapper.java:62)
	at com.mrcrayfish.vehicle.client.render.RenderMotorcycleWrapper.render(RenderMotorcycleWrapper.java:12)
	at com.mrcrayfish.vehicle.client.render.tileentity.JackRenderer.render(JackRenderer.java:111)
	at com.mrcrayfish.vehicle.client.render.tileentity.JackRenderer.render(JackRenderer.java:25)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.render(TileEntityRendererDispatcher.java:161)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.render(TileEntityRendererDispatcher.java:133)
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:732)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1400)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1312)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1115)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1208)
	at net.minecraft.client.Minecraft.run(Minecraft.java:441)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.vehicle.client.render.AbstractRenderVehicle.renderDamagedPart(AbstractRenderVehicle.java:115)
	at com.mrcrayfish.vehicle.client.render.AbstractRenderVehicle.renderDamagedPart(AbstractRenderVehicle.java:102)
	at com.mrcrayfish.vehicle.client.render.AbstractRenderVehicle.renderDamagedPart(AbstractRenderVehicle.java:96)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderMoped.render(RenderMoped.java:40)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderMoped.render(RenderMoped.java:19)
	at com.mrcrayfish.vehicle.client.render.RenderMotorcycleWrapper.render(RenderMotorcycleWrapper.java:62)
	at com.mrcrayfish.vehicle.client.render.RenderMotorcycleWrapper.render(RenderMotorcycleWrapper.java:12)
	at com.mrcrayfish.vehicle.client.render.tileentity.JackRenderer.render(JackRenderer.java:111)
	at com.mrcrayfish.vehicle.client.render.tileentity.JackRenderer.render(JackRenderer.java:25)

-- Block Entity Details --
Details:
	Name: vehicle:jack // com.mrcrayfish.vehicle.tileentity.TileEntityJack
	Block type: ID #443 (tile.jack // com.mrcrayfish.vehicle.block.BlockJack // vehicle:jack)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-894,63,1444), Chunk: (at 2,3,4 in -56,90; contains blocks -896,0,1440 to -881,255,1455), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
	Actual block type: ID #443 (tile.jack // com.mrcrayfish.vehicle.block.BlockJack // vehicle:jack)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.render(TileEntityRendererDispatcher.java:161)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.render(TileEntityRendererDispatcher.java:133)
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:732)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1400)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1312)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Player541'/40, l='MpServer', x=-892.11, y=63.00, z=1444.87]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-884,4,1460), Chunk: (at 12,0,4 in -56,91; contains blocks -896,0,1456 to -881,255,1471), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
	Level time: 49828 game time, 1132 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 8 total; [EntityItem['item.tile.fenceIron'/46288, l='MpServer', x=-893.71, y=64.15, z=1444.89], EntityItem['item.tile.cloth.black'/46289, l='MpServer', x=-893.59, y=63.78, z=1445.00], EntityItem['item.item.wheel'/46290, l='MpServer', x=-893.67, y=64.36, z=1444.94], EntityItem['item.item.small_engine'/46292, l='MpServer', x=-893.54, y=64.14, z=1444.74], EntityMoped['Moped'/46282, l='MpServer', x=-893.56, y=63.59, z=1444.93], EntityJack['entity.vehicle.jack.name'/46283, l='MpServer', x=-893.50, y=63.59, z=1444.50], EntityPlayerSP['Player541'/40, l='MpServer', x=-892.11, y=63.00, z=1444.87], EntityItem['item.item.ingotIron'/46287, l='MpServer', x=-893.45, y=64.26, z=1444.75]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:461)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2888)
	at net.minecraft.client.Minecraft.run(Minecraft.java:462)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_192, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 199899880 bytes (190 MB) / 940048384 bytes (896 MB) up to 940048384 bytes (896 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 14
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID             | Version       | Source                              | Signature                                |
	|:--------- |:-------------- |:------------- |:----------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft      | 1.12.2        | minecraft.jar                       | None                                     |
	| UCHIJAAAA | mcp            | 9.42          | minecraft.jar                       | None                                     |
	| UCHIJAAAA | FML            | 8.0.99.99     | forgeSrc-1.12.2-14.23.5.2768.jar    | None                                     |
	| UCHIJAAAA | forge          | 14.23.5.2768  | forgeSrc-1.12.2-14.23.5.2768.jar    | None                                     |
	| UCHIJAAAA | obfuscate      | 0.2.6         | minecraft.jar                       | None                                     |
	| UCHIJAAAA | nebulus        | 3.3.0         | modid-1.0.jar                       | None                                     |
	| UCHIJAAAA | ic2            | 2.8.100-ex112 | industrialcraft-2-2.8.100-ex112.jar | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | jei            | 4.11.0.202    | jei_1.12.2-4.11.0.202.jar           | None                                     |
	| UCHIJAAAA | ogameconsoles  | 1.0.0         | ogameconsoles-0.1.0.jar             | None                                     |
	| UCHIJAAAA | placeableitems | 3.3           | placeableitems-3.3 (1).jar          | None                                     |
	| UCHIJAAAA | twa            | 0.1           | twa-0.1.jar                         | None                                     |
	| UCHIJAAAA | vehicle        | 0.36.0        | vehicle-mod-0.36.0-1.12.2.jar       | None                                     |

	Loaded coremods (and transformers): 
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3304' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3304, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: newloadingscreen - Copy
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-3229Y CPU @ 1.40GHz

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/4ad9c8c1ae023e85b471779aceb278bf6a878da0
