### ISSUE TITLE
Crashing while loading

### ISSUE THREAD

**Issue by Nigelsiris** [MrCrayfish/MrCrayfishVehicleMod#150]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2019-08-14 10:41:22 EDT
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
    at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
    at com.mrcrayfish.furniture.init.RegistrationHandler$Blocks.lambda$register$0(RegistrationHandler.java:40)
    at com.mrcrayfish.furniture.init.RegistrationHandler$Blocks$$Lambda$4168/1465375820.accept(Unknown Source)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.mrcrayfish.furniture.init.RegistrationHandler$Blocks.register(RegistrationHandler.java:40)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_744_Blocks_register_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Nigelsiris** [comment]
Nvm Im dumb
