### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by yeeeeeeeeeeeeeeeeeeeeeeee** [MrCrayfish/MrCrayfishVehicleMod#173]
@MrCrayfish 
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 1/8/20 8:02 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.mrcrayfish.vehicle.client.EntityRaytracer.raytraceEntities(EntityRaytracer.java:1197) ~[?:0.42.0-beta-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.EntityRaytracer.performRayTrace(EntityRaytracer.java:1171) ~[?:0.42.0-beta-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.EntityRaytracer.onMouseEvent(EntityRaytracer.java:1162) ~[?:0.42.0-beta-1.15.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_28_EntityRaytracer_onMouseEvent_RawMouseEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onRawMouseClicked(ForgeHooksClient.java:963) ~[?:?] {re:classloading}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:69) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.1.jar:build 12] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.1.jar:build 12] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3129) ~[lwjgl-glfw-3.2.1.jar:build 12] {}
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:907) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:520) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:202) ~[1.15.1-forge-30.0.35.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.1-30.0.35.jar:30.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.1
	Minecraft Version ID: 1.15.1
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1425707016 bytes (1359 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.1-30.0.35.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.35.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.1-30.0.35.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.35.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.1-30.0.35.jar fml TRANSFORMATIONSERVICE 
	FML: 30.0
	Forge: net.minecraftforge:30.0.35
	FML Language Providers: 
		javafml@30.0
		minecraft@1
	Mod List: 
		forge-1.15.1-30.0.35-client.jar Minecraft {minecraft@1.15.1 DONE}
		obfuscate-0.3.4-1.15.1.jar Obfuscate {obfuscate@0.3.4 DONE}
		forge-1.15.1-30.0.35-universal.jar Forge {forge@30.0.35 DONE}
		cfm-7.0.0-pre16-mc1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		vehicle-0.42.0-mc1.15.1.jar MrCrayfish's Vehicle Mod {vehicle@0.42.0 DONE}
	Launched Version: 1.15.1-forge-30.0.35
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Intel(R) HD Graphics 6000 GL version 2.1 INTEL-10.36.26, Intel Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz

**Comment by MrCrayfish** [comment]
Download 0.42.1, fixed the issue.

**Comment by yeeeeeeeeeeeeeeeeeeeeeeee** [comment]
@MrCrayfish 0.42.1 what? Obfuscate, Vehicle Mod, Forge

**Comment by yeeeeeeeeeeeeeeeeeeeeeeee** [comment]
@MrCrayfish THX
