### ISSUE TITLE
Crash Rendering StorageTrailer

### ISSUE THREAD

**Issue by brumfb** [MrCrayfish/MrCrayfishVehicleMod#206]
We have run into an apparent issue rendering StorageTrailer. Crash report below, let me know if we can provide any more details or if you see something incompatible in our setup.

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 3/8/20 9:49 PM
Description: Rendering Block Entity

java.lang.NoSuchMethodError: net.minecraft.item.Item.getTileEntityItemStackRenderer()Lnet/minecraft/client/renderer/tileentity/ItemStackTileEntityRenderer;
	at com.mrcrayfish.vehicle.util.RenderUtil.renderModel(RenderUtil.java:138) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:52) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:21) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.RenderVehicleWrapper.render(RenderVehicleWrapper.java:68) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_225623_a_(RenderEntityVehicle.java:46) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_225623_a_(RenderEntityVehicle.java:17) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.tileentity.VehicleCrateRenderer.func_225616_a_(VehicleCrateRenderer.java:125) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.tileentity.VehicleCrateRenderer.func_225616_a_(VehicleCrateRenderer.java:28) ~[?:0.42.4-1.15.1] {re:classloading}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:100) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$func_228850_a_$0(TileEntityRendererDispatcher.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$5004/83503505.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:124) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:83) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:980) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:601) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:423) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:882) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:520) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:202) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.1-30.0.51.jar:30.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$408/842957574.call(Unknown Source) [forge-1.15.1-30.0.51.jar:30.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mrcrayfish.vehicle.util.RenderUtil.renderModel(RenderUtil.java:138)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:52)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:21)
	at com.mrcrayfish.vehicle.client.render.RenderVehicleWrapper.render(RenderVehicleWrapper.java:68)
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_225623_a_(RenderEntityVehicle.java:46)
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_225623_a_(RenderEntityVehicle.java:17)
	at com.mrcrayfish.vehicle.client.render.tileentity.VehicleCrateRenderer.func_225616_a_(VehicleCrateRenderer.java:125)
	at com.mrcrayfish.vehicle.client.render.tileentity.VehicleCrateRenderer.func_225616_a_(VehicleCrateRenderer.java:28)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$func_228850_a_$0(TileEntityRendererDispatcher.java:84)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$5004/83503505.run(Unknown Source)

-- Block Entity Details --
Details:
	Name: vehicle:vehicle_crate // com.mrcrayfish.vehicle.tileentity.VehicleCrateTileEntity
	Block: Block{vehicle:vehicle_crate}[facing=north]
	Block location: World: (172,63,-221), Chunk: (at 12,3,3 in 10,-14; contains blocks 160,0,-224 to 175,255,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Block: Block{vehicle:vehicle_crate}[facing=north]
	Block location: World: (172,63,-221), Chunk: (at 12,3,3 in 10,-14; contains blocks 160,0,-224 to 175,255,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:124)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:83)
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:980)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:601)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['bsourcegaming'/175, l='MpServer', x=172.84, y=64.00, z=-217.53]]
	Chunk stats: Client Chunk Cache: 841, 529
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 4300170750181397574
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (176,65,-208), Chunk: (at 0,4,0 in 11,-13; contains blocks 176,0,-208 to 191,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 487 game time, 487 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1719)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:534)
	at net.minecraft.client.main.Main.main(SourceFile:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$408/842957574.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.1
	Minecraft Version ID: 1.15.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 782458680 bytes (746 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.1-30.0.51.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.51.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.1-30.0.51.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.51.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.1-30.0.51.jar fml TRANSFORMATIONSERVICE 
	FML: 30.0
	Forge: net.minecraftforge:30.0.51
	FML Language Providers: 
		javafml@30.0
		minecraft@1
	Mod List: 
		forge-1.15.1-30.0.51-client.jar Minecraft {minecraft@1.15.1 DONE}
		obfuscate-0.3.4-1.15.2.jar Obfuscate {obfuscate@0.3.4 DONE}
		forge-1.15.1-30.0.51-universal.jar Forge {forge@30.0.51 DONE}
		cfm-7.0.0-pre16-mc1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		vehicle-0.42.4-mc1.15.1.jar MrCrayfish's Vehicle Mod {vehicle@0.42.4 DONE}
	Launched Version: 1.15.1-forge-30.0.51
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 630 GL version 4.5.0 - Build 22.20.16.4836, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
```

**Comment by MrCrayfish** [comment]
This is fixed on 1.15.2. Please update as 1.15.1 is no longer supported. I see you're using my mods which I know are all updated.
