### ISSUE TITLE
Crash when picked up vehicle in a server 1.14.4

### ISSUE THREAD

**Issue by Kewin05c** [MrCrayfish/MrCrayfishVehicleMod#210]
If you place it down while looking at the floor it will crash but if you throw it without looking at the floor it wont crash

**Comment by Kewin05c** [comment]
If you place it down while looking at the floor it will crash but if you throw it without looking at the floor it wont crash

**Comment by MrCrayfish** [comment]
SEND A CRASH REPORT!

**Comment by Kewin05c** [comment]
---- Minecraft Crash Report ----
// There are four lights!

Time: 11/03/20 17:34
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerEntity.func_213324_a(DFZ)Lnet/minecraft/util/math/RayTraceResult;
	at com.mrcrayfish.vehicle.common.CommonEvents.onPlayerInteract(CommonEvents.java:264) ~[?:0.43.2-1.14.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_26_CommonEvents_onPlayerInteract_RightClickBlock.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:782) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:313) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:847) ~[?:?] {re:classloading,xf:fml:backpacked:creative_inventory_action_fix}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2977106880 bytes (2839 MB) / 4000841728 bytes (3815 MB) up to 4000841728 bytes (3815 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xmx4000M -Xms4000M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.0
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.0-server.jar Minecraft {minecraft@1.14.4 DONE}
		obfuscate-0.3.3-1.14.4.jar Obfuscate {obfuscate@0.3.3 DONE}
		petyourwolf-1.2.1-mc1.14.4.jar Pet Your Wolf {petyourwolf@1.2.1 DONE}
		forge-1.14.4-28.2.0-universal.jar Forge {forge@28.2.0 DONE}
		curios-FORGE-1.14.4-1.0.6.1.jar Curios API {curios@FORGE-1.14.4-1.0.6.1 DONE}
		backpacked-1.4.0-mc1.14.4.jar Backpacked {backpacked@1.4.0 DONE}
		slopes-1.0.0-mc1.14.4.jar Slopes {slopes@1.0.0 DONE}
		MoneyMod_1.14.4.jar Coins Mod {coins_mod@1.0.0 DONE}
		cfm-7.0.0-pre15-mc1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre15 DONE}
		vehicle-mod-0.43.2-1.14.4.jar MrCrayfish's Vehicle Mod {vehicle@0.43.2 DONE}
		StorageDrawers-1.14.4-6.0.6.jar Storage Drawers {storagedrawers@1.14.4-6.0.6 DONE}
		enchantable-1.1.0-mc1.14.4.jar Enchantable {enchantable@1.1.0 DONE}
	Player Count: 2 / 20; [ServerPlayerEntity['Kewin05c'/133, l='world', x=-74.81, y=68.00, z=108.32], ServerPlayerEntity['TheNoobiestYT'/135, l='world', x=-76.79, y=68.00, z=98.68]]
	Data Packs: vanilla, mod:backpacked, mod:cfm, mod:enchantable, mod:forge, mod:obfuscate, mod:petyourwolf, mod:slopes, mod:coins_mod, mod:curios, mod:storagedrawers, mod:vehicle
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by LoyaltyGamer72** [comment]
I have the same problem with the same starting lines on my crash report, if it would help I can send it too

**Comment by otvando** [comment]
i have the same problem, i am running version 43.3

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishVehicleMod/commit/62ee60ab442913f2cf84c86c9a241f6c1dc157de
