### ISSUE TITLE
Vehicle parsing error

### ISSUE THREAD

**Issue by Ziefin** [MrCrayfish/MrCrayfishVehicleMod#211]
[15:49:02] [Server thread/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe vehicle:boost_pad
com.google.gson.JsonSyntaxException: Unknown item 'vehicle:boost_pad'
        at net.minecraft.item.crafting.ShapedRecipe.lambda$deserializeItem$0(ShapedRecipe.java:264) ~[?:?] {re:classloading}
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_201] {}
        at net.minecraft.item.crafting.ShapedRecipe.func_199798_a(ShapedRecipe.java:263) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:283) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:274) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}  
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:60) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}  
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:37) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}  
        at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_201] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_201] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_201] {}
        at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}     
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:729) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}     
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:712) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:706) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:classloading,pl:accesstransformer:B}     
        at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1458) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:448) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:361) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:211) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:611) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201] {}

**Comment by LoyaltyGamer72** [comment]
Same error with the boost pad on 1.14

**Comment by MrCrayfish** [comment]
Don't worry about it for now. It's simply because the boost pad doesn't exist right now in newer versions of the mod however the recipe definition is still loaded. Your world or server will still start fine.
