### ISSUE TITLE
Crash on creating world 

### ISSUE THREAD

**Issue by zaneker** [MrCrayfish/MrCrayfishVehicleMod#232]
I've been getting this issue consistently since yesterday and can't seem to find a solution. I've already tried an older version of forge as well as completely reinstalling my video drivers.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ObfuscatePlugin (obfuscate-0.4.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 3/28/20 4:29 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at com.mrcrayfish.obfuscate.common.data.SyncedPlayerData$Provider.<init>(SyncedPlayerData.java:457)
	at com.mrcrayfish.obfuscate.common.data.SyncedPlayerData.attachCapabilities(SyncedPlayerData.java:174)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_SyncedPlayerData_attachCapabilities_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:661)
	at net.minecraft.entity.Entity.<init>(Entity.java:219)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:164)
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:157)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:158)
	at net.minecraft.server.management.PlayerList.func_148545_a(PlayerList.java:504)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:135)
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.mrcrayfish.obfuscate.common.data.SyncedPlayerData$Provider.<init>(SyncedPlayerData.java:457)
	at com.mrcrayfish.obfuscate.common.data.SyncedPlayerData.attachCapabilities(SyncedPlayerData.java:174)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_SyncedPlayerData_attachCapabilities_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:661)
	at net.minecraft.entity.Entity.<init>(Entity.java:219)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:164)
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:157)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:158)
	at net.minecraft.server.management.PlayerList.func_148545_a(PlayerList.java:504)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:135)
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@4470a825
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 242349864 bytes (231 MB) / 536870912 bytes (512 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 9, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                         | Signature |
	|:------ |:--------- |:------------ |:------------------------------ |:--------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                  | None      |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                  | None      |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar  | None      |
	| LCHIJA | forge     | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar  | None      |
	| LCHIJA | obfuscate | 0.4.0        | minecraft.jar                  | None      |
	| LCHIJA | vehicle   | 0.43.4       | vehicle-0.43.4-mc1.12.2(1).jar | None      |

	Loaded coremods (and transformers): 
ObfuscatePlugin (obfuscate-0.4.1-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by MrCrayfish** [comment]
Fixed in 0.4.2
