### ISSUE TITLE
VEHICLES NOT WORKING ON FORGE SERVER

### ISSUE THREAD

**Issue by tinchocore** [MrCrayfish/MrCrayfishVehicleMod#242]
I  have a server where i play with my friends and for some reason we cant drive the vehicles on the server. I tried to drive them in SP with the same modpack and in SP they work just fine.

**Comment by AngelAlvarado** [comment]
Same here!

these are the errors we are getting

```
forgedockerfile1151 | java.io.FileNotFoundException: https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/vehicle/update.json
forgedockerfile1151 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:189) ~[?:?] {re:classloading}
forgedockerfile1151 | 	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:206) ~[?:?] {re:classloading}
forgedockerfile1151 | 	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_171] {}
forgedockerfile1151 | 	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:157) [?:?] {re:classloading}
forgedockerfile1151 | Caused by: java.io.FileNotFoundException: https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/vehicle/update.json
forgedockerfile1151 | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:173) ~[?:?] {re:classloading}
forgedockerfile1151 | 	... 3 more
```

```
forgedockerfile1151 | com.google.gson.JsonSyntaxException: Unknown item 'vehicle:boost_pad'
forgedockerfile1151 | 	at net.minecraft.item.crafting.ShapedRecipe.lambda$deserializeItem$0(ShapedRecipe.java:264) ~[?:?] {re:classloading}
forgedockerfile1151 | 	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at net.minecraft.item.crafting.ShapedRecipe.func_199798_a(ShapedRecipe.java:263) ~[?:?] {re:classloading}
forgedockerfile1151 | 	at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:283) ~[?:?] {re:classloading}
forgedockerfile1151 | 	at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:274) ~[?:?] {re:classloading}
forgedockerfile1151 | 	at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
forgedockerfile1151 | 	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:60) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
forgedockerfile1151 | 	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:37) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
forgedockerfile1151 | 	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:classloading}
forgedockerfile1151 | 	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_171] {}
forgedockerfile1151 | 	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
forgedockerfile1151 | 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?] {re:classloading}
forgedockerfile1151 | 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}
forgedockerfile1151 | 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
forgedockerfile1151 | 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}
forgedockerfile1151 | 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:711) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
forgedockerfile1151 | 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:705) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
forgedockerfile1151 | 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:classloading,pl:accesstransformer:B}
forgedockerfile1151 | 	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1449) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
forgedockerfile1151 | 	at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:447) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
forgedockerfile1151 | 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:360) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
forgedockerfile1151 | 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) [?:?] {re:classloading,pl:accesstransformer:B}
forgedockerfile1151 | 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:610) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
forgedockerfile1151 | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171] {}
```

Maybe it's just not compatible at all in Forge Server?

**Comment by MrCrayfish** [comment]
Those errors are unrelated. I will look into the issue. If this was widespread, I would have known about the issue earlier but it could be the setup of your server. I will need more information of the issue. Can you post screenshots/video of you trying to drive the vehicles and a list of mods on the server and clients? There is not a lot I can do when I dont have information like this.

**Comment by MrFlorentin** [comment]
Same problem here !
But, no error in logs, but I have screenshots. Here :
![image](https://user-images.githubusercontent.com/52799467/81279998-29247b80-9058-11ea-8091-6aeb9a3d8d03.png) 
![image](https://user-images.githubusercontent.com/52799467/81280015-32ade380-9058-11ea-9d9c-f7ff414b043f.png)


On the next image, I took the vehicle over my head, and there is no animation and I can't see it.
![image](https://user-images.githubusercontent.com/52799467/81280117-56712980-9058-11ea-95be-6cee4af0e71d.png)

![image](https://user-images.githubusercontent.com/52799467/81280226-73a5f800-9058-11ea-8a22-a3588bf020cf.png)
![image](https://user-images.githubusercontent.com/52799467/81280289-89b3b880-9058-11ea-96b3-ac352e7d347f.png)

**Comment by arthurcorso** [comment]
moi aussi

**Comment by MrCrayfish** [comment]
Are you using a custom server software? Most hybrid bukkit + forge servers break lots of mods due to failing to keep the same behaviour of forge. Closing for now since anything under 1.16 I will no longer be supporting.
