### ISSUE TITLE
The mod crash

### ISSUE THREAD

**Issue by Gabriel44200** [MrCrayfish/MrCrayfishVehicleMod#254]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.9_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 4/28/20 1:28 PM
Description: Unexpected error

java.lang.VerifyError: (class: javax/vecmath/Tuple3d, method: scaleAdd signature: (DLjavax/vecmath/Tuple3f;)V) Incompatible argument to function
	at com.mrcrayfish.vehicle.client.EntityRaytracer$MatrixTransformation.transform(EntityRaytracer.java:1166)
	at com.mrcrayfish.vehicle.client.EntityRaytracer.registerEntityStatic(EntityRaytracer.java:930)
	at com.mrcrayfish.vehicle.client.EntityRaytracer.registerEntitiesStatic(EntityRaytracer.java:224)
	at com.mrcrayfish.vehicle.client.EntityRaytracer.init(EntityRaytracer.java:859)
	at com.mrcrayfish.vehicle.client.EntityRaytracer.raytraceEntitiesContinuously(EntityRaytracer.java:1202)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_55_EntityRaytracer_raytraceEntitiesContinuously_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.vehicle.client.EntityRaytracer$MatrixTransformation.transform(EntityRaytracer.java:1166)
	at com.mrcrayfish.vehicle.client.EntityRaytracer.registerEntityStatic(EntityRaytracer.java:930)
	at com.mrcrayfish.vehicle.client.EntityRaytracer.registerEntitiesStatic(EntityRaytracer.java:224)
	at com.mrcrayfish.vehicle.client.EntityRaytracer.init(EntityRaytracer.java:859)
	at com.mrcrayfish.vehicle.client.EntityRaytracer.raytraceEntitiesContinuously(EntityRaytracer.java:1202)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_55_EntityRaytracer_raytraceEntitiesContinuously_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['_Gabriel_'/308, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['_Gabriel_'/308, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3428024640 bytes (3269 MB) / 4898947072 bytes (4672 MB) up to 13723762688 bytes (13088 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx13084M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version                     | Source                                            | Signature |
	|:------ |:----------------- |:--------------------------- |:------------------------------------------------- |:--------- |
	| LCHIJA | minecraft         | 1.12.2                      | minecraft.jar                                     | None      |
	| LCHIJA | mcp               | 9.42                        | minecraft.jar                                     | None      |
	| LCHIJA | FML               | 8.0.99.99                   | forge-1.12.2-14.23.5.2847.jar                     | None      |
	| LCHIJA | forge             | 14.23.5.2847                | forge-1.12.2-14.23.5.2847.jar                     | None      |
	| LCHIJA | creativecoredummy | 1.0.0                       | minecraft.jar                                     | None      |
	| LCHIJA | obfuscate         | 0.4.2                       | minecraft.jar                                     | None      |
	| LCHIJA | srm-hooks         | 1.12.2-1.0.0                | minecraft.jar                                     | None      |
	| LCHIJA | securitycraft     | v1.8.17                     | %5b1.12.2%5d+SecurityCraft+v1.8.17.jar            | None      |
	| LCHIJA | ctm               | MC1.12.2-1.0.1.30           | CTM-MC1.12.2-1.0.1.30.jar                         | None      |
	| LCHIJA | chisel            | MC1.12.2-1.0.1.44           | Chisel-MC1.12.2-1.0.1.44.jar                      | None      |
	| LCHIJA | chococraft        | 0.9.8.0                     | chococraft_1.12.2-0.9.8.0.jar                     | None      |
	| LCHIJA | opframe           | 1.4.0                       | OnlinePicFrame_v1.4.35_mc1.12.2.jar               | None      |
	| LCHIJA | creativecore      | 1.10.0                      | CreativeCore_v1.10.9_mc1.12.2.jar                 | None      |
	| LCHIJA | modcurrency       | 1.12.0-2.0.0-ALPHA-20200315 | Currency-1.12.0-2.0.0-ALPHA-20200315.jar          | None      |
	| LCHIJA | ptrmodellib       | 1.0.4                       | PTRLib-1.0.4.jar                                  | None      |
	| LCHIJA | props             | 2.6.3                       | Decocraft-2.6.3_1.12.2.jar                        | None      |
	| LCHIJA | extrautils2       | 1.0                         | extrautils2-1.12-1.9.9.jar                        | None      |
	| LCHIJA | journeymap        | 1.12.2-5.7.1                | journeymap-1.12.2-5.7.1.jar                       | None      |
	| LCHIJA | ngtlib            | 2.4.17                      | NGTLib2.4.17-33_forge-1.12.2-14.23.2.2611.jar     | None      |
	| LCHIJA | rtm               | 2.4.19                      | RTM2.4.19-37_forge-1.12.2-14.23.2.2611.jar        | None      |
	| LCHIJA | rustic            | 1.1.2                       | rustic-1.1.2.jar                                  | None      |
	| LCHIJA | secretroomsmod    | 5.6.4                       | secretroomsmod-1.12.2-5.6.4.jar                   | None      |
	| LCHIJA | vehicle           | 0.43.5                      | vehicle-mod-0.43.5-1.12.2.jar                     | None      |
	| LCHIJA | worldedit         | 6.1.10-SNAPSHOT             | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None      |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CreativePatchingLoader (CreativeCore_v1.10.9_mc1.12.2.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13587 Compatibility Profile Context 20.2.2 26.20.15019.19000' Renderer: 'AMD 15D8:C8'
	Launched Version: maincra
	LWJGL: 2.9.4
	OpenGL: AMD 15D8:C8 GL version 4.6.13587 Compatibility Profile Context 20.2.2 26.20.15019.19000, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 5 3400G with Radeon Vega Graphics

**Comment by Gabriel44200** [comment]
Why is the game crash?
