### ISSUE TITLE
"Rendering screen" Crash

### ISSUE THREAD

**Issue by BlueYoshi68** [MrCrayfish/MrCrayfishVehicleMod#258]
Not really sure if this project is even being worked on anymore but I guess ill post this here anyway.

`java.lang.NullPointerException
    at com.mrcrayfish.vehicle.client.gui.GuiFluidMixer.drawGuiContainerBackgroundLayer(GuiFluidMixer.java:126)
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:75)
    at com.mrcrayfish.vehicle.client.gui.GuiFluidMixer.drawScreen(GuiFluidMixer.java:42)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1456)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by DevWolf31** [comment]
Apparently it is a problem with Optifine since I see that among the errors is a class of Optifine. I don't know if this helped you, but I did what I could
