### ISSUE TITLE
Game crashes when the mod Pollution of the Realms is installed

### ISSUE THREAD

**Issue by Alex34fggh** [MrCrayfish/MrCrayfishVehicleMod#283]
Here is the crash log for more info. The version that I was using is 1.12.2.

[14:32:13] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:32:13] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:32:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[14:32:13] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[14:32:13] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_212, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_212
[14:32:13] [main/INFO] [FML]: Searching D:\aoi\mods for mods
[14:32:13] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AdPother-1.12.2-1.2.6.0-build.0510.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[14:32:13] [main/WARN] [FML]: The coremod com.endertech.minecraft.mods.adpother.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:32:13] [main/WARN] [FML]: The coremod LoadingPlugin (com.endertech.minecraft.mods.adpother.LoadingPlugin) is not signed!
[14:32:13] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[14:32:13] [main/WARN] [FML]: The coremod com.endertech.minecraft.forge.coremod.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:32:13] [main/WARN] [FML]: The coremod CorePlugin (com.endertech.minecraft.forge.coremod.CorePlugin) is not signed!
[14:32:13] [main/WARN] [FML]: The coremod ObfuscatePlugin (com.mrcrayfish.obfuscate.asm.ObfuscatePlugin) is not signed!
[14:32:13] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:32:13] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[14:32:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:32:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:32:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:32:16] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[14:32:16] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[14:32:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:32:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:32:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:32:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[14:32:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:32:18] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[14:32:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[14:32:18] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[14:32:20] [Client thread/INFO] [minecraft/Minecraft]: Setting user: ALex
[14:32:25] [Client thread/WARN] [minecraft/GameSettings]: Skipping bad option: lastServer:
[14:32:25] [Client thread/INFO] [minecraft/Minecraft]: LWJGL Version: 2.9.4
[14:32:26] [Client thread/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 120064504 bytes (114 MB) / 286273536 bytes (273 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
LoadingPlugin (AdPother-1.12.2-1.2.6.0-build.0510.jar)
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Vanilla
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$DynamicSurroundings
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Weather2$Mesh
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Weather2$Render
  com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$FurnaceDouble
  com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$CoalGenerator
  com.endertech.minecraft.mods.adpother.transformers.BetterWithMods$Furnace
  com.endertech.minecraft.mods.adpother.transformers.ControlledBurn$Fire
  com.endertech.minecraft.mods.adpother.transformers.CookingForBlockheads$Oven
  com.endertech.minecraft.mods.adpother.transformers.DraconicEvolution$Generator
  com.endertech.minecraft.mods.adpother.transformers.EmbersRekindled$EmberBore
  com.endertech.minecraft.mods.adpother.transformers.EmbersRekindled$SteamEngine
  com.endertech.minecraft.mods.adpother.transformers.EnderIO$StirlingGenerator
  com.endertech.minecraft.mods.adpother.transformers.EngineersDecor$DecorFurnace
  com.endertech.minecraft.mods.adpother.transformers.Factory0Resources$BurnerDrill
  com.endertech.minecraft.mods.adpother.transformers.FastFurnace$Burning
  com.endertech.minecraft.mods.adpother.transformers.FastFurnace$Smelting
  com.endertech.minecraft.mods.adpother.transformers.FurnaceOverhaul$Burning
  com.endertech.minecraft.mods.adpother.transformers.FurnaceOverhaul$Smelting
  com.endertech.minecraft.mods.adpother.transformers.FutureMC$AdvancedFurnace
  com.endertech.minecraft.mods.adpother.transformers.FloodLights$CarbonFloodlight
  com.endertech.minecraft.mods.adpother.transformers.Galacticraft$AutoRocket
  com.endertech.minecraft.mods.adpother.transformers.Galacticraft$Buggy
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveCraft$FurnaceTE
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityCokeOven
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityBlastFurnace
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityDieselGenerator
  com.endertech.minecraft.mods.adpother.transformers.ImmersivePetroleum$Motorboat
  com.endertech.minecraft.mods.adpother.transformers.ImmersivePetroleum$PortableGenerator
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveRailroading$LocomotiveDiesel
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveRailroading$LocomotiveSteam
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveTechnology$Boiler
  com.endertech.minecraft.mods.adpother.transformers.Magneticraft$CombustionChamber
  com.endertech.minecraft.mods.adpother.transformers.Magneticraft$BigChamberSolidFuel
  com.endertech.minecraft.mods.adpother.transformers.Magneticraft$BigChamberLiquidFuel
  com.endertech.minecraft.mods.adpother.transformers.Mekanism$FuelwoodHeater
  com.endertech.minecraft.mods.adpother.transformers.Metallurgy$Alloyer
  com.endertech.minecraft.mods.adpother.transformers.Metallurgy$Crusher
  com.endertech.minecraft.mods.adpother.transformers.Minecraft$AnimalFeeding
  com.endertech.minecraft.mods.adpother.transformers.Minecraft$FurnaceSmelting
  com.endertech.minecraft.mods.adpother.transformers.MoreFurnaces$IronFurnace
  com.endertech.minecraft.mods.adpother.transformers.MrCrayfish$Vehicle
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$InferiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$IntermediumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$PrudentiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SuperiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SupremiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$UltimateFurnace
  com.endertech.minecraft.mods.adpother.transformers.Natura$NetherrackFurnace
  com.endertech.minecraft.mods.adpother.transformers.PneumaticCraft$AirCompressor
  com.endertech.minecraft.mods.adpother.transformers.PrimalCore$RecipeHelper
  com.endertech.minecraft.mods.adpother.transformers.Pyrotech$TileCombustion
  com.endertech.minecraft.mods.adpother.transformers.RealisticBlockPhysics$FallingBlock
  com.endertech.minecraft.mods.adpother.transformers.RealisticTorches$BlockTorch
  com.endertech.minecraft.mods.adpother.transformers.RFTools$CoalGenerator
  com.endertech.minecraft.mods.adpother.transformers.StevesCarts$ModuleCoal
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronAlloyFurnace
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronFurnace
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileSolidFuelGenerator
  com.endertech.minecraft.mods.adpother.transformers.TinkersComplement$HighOven
  com.endertech.minecraft.mods.adpother.transformers.TinkersConstruct$HeatingStructure
  com.endertech.minecraft.mods.adpother.transformers.SimpleGrinder$CoalGrinder
  com.endertech.minecraft.mods.adpother.transformers.UltimateCarMod$Car
  com.endertech.minecraft.mods.adpother.transformers.ViesCraft$AirShip
  com.endertech.minecraft.mods.adpother.renders.AerometerRender
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockCaughtFire
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockUpdateTick
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockExploded
  com.endertech.minecraft.mods.adpother.pollution.WorldData$GetSkyColor
  com.endertech.minecraft.mods.adpother.pollution.WorldData$FurnaceFuelBurned
  com.endertech.minecraft.mods.adpother.pollution.WorldData$LavaTouchesWater
  com.endertech.minecraft.mods.adpother.transformers.ZenFoundry$BurnerHeater
  com.endertech.minecraft.mods.adpother.transformers.ZenFoundry$MoldStation
CorePlugin (ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar)
  
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.20.16.4973' Renderer: 'Intel(R) HD Graphics 520'
[14:32:26] [Client thread/INFO] [FML]: MinecraftForge v14.23.5.2854 Initialized
[14:32:26] [Client thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[14:32:26] [Client thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[14:32:27] [Client thread/INFO] [FML]: Replaced 1227 ore ingredients
[14:32:28] [Client thread/INFO] [FML]: Searching D:\aoi\mods for mods
[14:32:29] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 120515000 nanos
[14:32:30] [Client thread/INFO] [FML]: Forge Mod Loader has identified 8 mods to load
[14:32:30] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, obfuscate, adpother, forgeendertech, vehicle] at CLIENT
[14:32:30] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, obfuscate, adpother, forgeendertech, vehicle] at SERVER
[14:32:32] [Client thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Pollution of the Realms, FMLFileResourcePack:Forge Endertech, FMLFileResourcePack:MrCrayfish's Vehicle Mod
[14:32:32] [Client thread/INFO] [Obfuscate]: Applying ASM to RenderItem
[14:32:32] [Client thread/INFO] [Obfuscate]: Successfully patched RenderItem
[14:32:32] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[14:32:32] [Client thread/INFO] [FML]: Found 1237 ObjectHolder annotations
[14:32:32] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[14:32:32] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[14:32:32] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[14:32:32] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[14:32:32] [Client thread/INFO] [Obfuscate]: Successfully injected SyncedPlayerData capability
[14:32:33] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: UP_TO_DATE Target: null
[14:32:36] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (AdPother-1.12.2-1.2.6.0-build.0510.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 6/12/20 2:32 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MrCrayfish's Vehicle Mod (vehicle)
Caused by: java.lang.NoClassDefFoundError: com/mrcrayfish/vehicle/entity/vehicle/EntityATV
	at com.mrcrayfish.vehicle.VehicleMod.registerVehicles(VehicleMod.java:104)
	at com.mrcrayfish.vehicle.VehicleMod.onPreInit(VehicleMod.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.mrcrayfish.vehicle.entity.vehicle.EntityATV
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
Caused by: java.lang.NoClassDefFoundError: com/mrcrayfish/vehicle/entity/EntityLandVehicle
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more
Caused by: java.lang.ClassNotFoundException: com.mrcrayfish.vehicle.entity.EntityLandVehicle
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 49 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 86211128 bytes (82 MB) / 328232960 bytes (313 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version        | Source                                       | Signature                                |
	|:----- |:-------------- |:-------------- |:-------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft      | 1.12.2         | minecraft.jar                                | None                                     |
	| LCH   | mcp            | 9.42           | minecraft.jar                                | None                                     |
	| LCH   | FML            | 8.0.99.99      | forge-1.12.2-14.23.5.2854.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge          | 14.23.5.2854   | forge-1.12.2-14.23.5.2854.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | obfuscate      | 0.4.2          | minecraft.jar                                | None                                     |
	| LCH   | forgeendertech | 1.12.2-4.5.2.0 | ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar | None                                     |
	| LCH   | adpother       | 1.12.2-1.2.6.0 | AdPother-1.12.2-1.2.6.0-build.0510.jar       | None                                     |
	| LCE   | vehicle        | 0.44.1         | vehicle-mod-0.44.1-1.12.2.jar                | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (AdPother-1.12.2-1.2.6.0-build.0510.jar)
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Vanilla
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$DynamicSurroundings
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Weather2$Mesh
  com.endertech.minecraft.mods.adpother.transformers.AcidRain$Weather2$Render
  com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$FurnaceDouble
  com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$CoalGenerator
  com.endertech.minecraft.mods.adpother.transformers.BetterWithMods$Furnace
  com.endertech.minecraft.mods.adpother.transformers.ControlledBurn$Fire
  com.endertech.minecraft.mods.adpother.transformers.CookingForBlockheads$Oven
  com.endertech.minecraft.mods.adpother.transformers.DraconicEvolution$Generator
  com.endertech.minecraft.mods.adpother.transformers.EmbersRekindled$EmberBore
  com.endertech.minecraft.mods.adpother.transformers.EmbersRekindled$SteamEngine
  com.endertech.minecraft.mods.adpother.transformers.EnderIO$StirlingGenerator
  com.endertech.minecraft.mods.adpother.transformers.EngineersDecor$DecorFurnace
  com.endertech.minecraft.mods.adpother.transformers.Factory0Resources$BurnerDrill
  com.endertech.minecraft.mods.adpother.transformers.FastFurnace$Burning
  com.endertech.minecraft.mods.adpother.transformers.FastFurnace$Smelting
  com.endertech.minecraft.mods.adpother.transformers.FurnaceOverhaul$Burning
  com.endertech.minecraft.mods.adpother.transformers.FurnaceOverhaul$Smelting
  com.endertech.minecraft.mods.adpother.transformers.FutureMC$AdvancedFurnace
  com.endertech.minecraft.mods.adpother.transformers.FloodLights$CarbonFloodlight
  com.endertech.minecraft.mods.adpother.transformers.Galacticraft$AutoRocket
  com.endertech.minecraft.mods.adpother.transformers.Galacticraft$Buggy
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveCraft$FurnaceTE
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityCokeOven
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityBlastFurnace
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityDieselGenerator
  com.endertech.minecraft.mods.adpother.transformers.ImmersivePetroleum$Motorboat
  com.endertech.minecraft.mods.adpother.transformers.ImmersivePetroleum$PortableGenerator
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveRailroading$LocomotiveDiesel
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveRailroading$LocomotiveSteam
  com.endertech.minecraft.mods.adpother.transformers.ImmersiveTechnology$Boiler
  com.endertech.minecraft.mods.adpother.transformers.Magneticraft$CombustionChamber
  com.endertech.minecraft.mods.adpother.transformers.Magneticraft$BigChamberSolidFuel
  com.endertech.minecraft.mods.adpother.transformers.Magneticraft$BigChamberLiquidFuel
  com.endertech.minecraft.mods.adpother.transformers.Mekanism$FuelwoodHeater
  com.endertech.minecraft.mods.adpother.transformers.Metallurgy$Alloyer
  com.endertech.minecraft.mods.adpother.transformers.Metallurgy$Crusher
  com.endertech.minecraft.mods.adpother.transformers.Minecraft$AnimalFeeding
  com.endertech.minecraft.mods.adpother.transformers.Minecraft$FurnaceSmelting
  com.endertech.minecraft.mods.adpother.transformers.MoreFurnaces$IronFurnace
  com.endertech.minecraft.mods.adpother.transformers.MrCrayfish$Vehicle
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$InferiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$IntermediumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$PrudentiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SuperiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SupremiumFurnace
  com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$UltimateFurnace
  com.endertech.minecraft.mods.adpother.transformers.Natura$NetherrackFurnace
  com.endertech.minecraft.mods.adpother.transformers.PneumaticCraft$AirCompressor
  com.endertech.minecraft.mods.adpother.transformers.PrimalCore$RecipeHelper
  com.endertech.minecraft.mods.adpother.transformers.Pyrotech$TileCombustion
  com.endertech.minecraft.mods.adpother.transformers.RealisticBlockPhysics$FallingBlock
  com.endertech.minecraft.mods.adpother.transformers.RealisticTorches$BlockTorch
  com.endertech.minecraft.mods.adpother.transformers.RFTools$CoalGenerator
  com.endertech.minecraft.mods.adpother.transformers.StevesCarts$ModuleCoal
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronAlloyFurnace
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronFurnace
  com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileSolidFuelGenerator
  com.endertech.minecraft.mods.adpother.transformers.TinkersComplement$HighOven
  com.endertech.minecraft.mods.adpother.transformers.TinkersConstruct$HeatingStructure
  com.endertech.minecraft.mods.adpother.transformers.SimpleGrinder$CoalGrinder
  com.endertech.minecraft.mods.adpother.transformers.UltimateCarMod$Car
  com.endertech.minecraft.mods.adpother.transformers.ViesCraft$AirShip
  com.endertech.minecraft.mods.adpother.renders.AerometerRender
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockCaughtFire
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockUpdateTick
  com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockExploded
  com.endertech.minecraft.mods.adpother.pollution.WorldData$GetSkyColor
  com.endertech.minecraft.mods.adpother.pollution.WorldData$FurnaceFuelBurned
  com.endertech.minecraft.mods.adpother.pollution.WorldData$LavaTouchesWater
  com.endertech.minecraft.mods.adpother.transformers.ZenFoundry$BurnerHeater
  com.endertech.minecraft.mods.adpother.transformers.ZenFoundry$MoldStation
CorePlugin (ForgeEndertech-1.12.2-4.5.2.0-build.0459.jar)
  
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.20.16.4973' Renderer: 'Intel(R) HD Graphics 520'
[14:32:36] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# D:\aoi\crash-reports\crash-2020-06-12_14.32.36-client.txt
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by MrCrayfish** [comment]
It's Pollution of the Realms fault. It uses a transformer that modifies my vehicle class. It obviously needs updating for it to work. Unfortunately they don't have a GitHub repo...
