### ISSUE TITLE
[Need Help] When I try to spawn the storage trailer it crashes my game

### ISSUE THREAD

**Issue by Tocoz** [MrCrayfish/MrCrayfishVehicleMod#287]
Whenever I try to spawn the storage trailer in creative it crashes my game or when I look at it in the workbench it will crash my game I'm using version 1.15.1

---- Minecraft Crash Report ----
// My bad.

Time: 6/16/20 7:20 PM
Description: Rendering entity in world

java.lang.NoSuchMethodError: net.minecraft.item.Item.getTileEntityItemStackRenderer()Lnet/minecraft/client/renderer/tileentity/ItemStackTileEntityRenderer;
	at com.mrcrayfish.vehicle.util.RenderUtil.renderModel(RenderUtil.java:138) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:52) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:21) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.RenderVehicleWrapper.render(RenderVehicleWrapper.java:68) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_225623_a_(RenderEntityVehicle.java:46) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_225623_a_(RenderEntityVehicle.java:17) ~[?:0.42.4-1.15.1] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:245) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.mrcrayfish.vehicle.client.screen.WorkstationScreen.func_146976_a(WorkstationScreen.java:470) ~[?:0.42.4-1.15.1] {re:classloading}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.render(ContainerScreen.java:73) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mrcrayfish.vehicle.client.screen.WorkstationScreen.render(WorkstationScreen.java:313) ~[?:0.42.4-1.15.1] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:365) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:882) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:520) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:202) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.1-30.0.51.jar:30.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$400/1642308093.call(Unknown Source) [forge-1.15.1-30.0.51.jar:30.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mrcrayfish.vehicle.util.RenderUtil.renderModel(RenderUtil.java:138)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:52)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:21)
	at com.mrcrayfish.vehicle.client.render.RenderVehicleWrapper.render(RenderVehicleWrapper.java:68)
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_225623_a_(RenderEntityVehicle.java:46)
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_225623_a_(RenderEntityVehicle.java:17)

-- Entity being rendered --
Details:
	Entity Type: vehicle:storage_trailer (com.mrcrayfish.vehicle.entity.trailer.StorageTrailerEntity)
	Entity ID: 477
	Entity Name: Storage Trailer
	Entity's Exact location: 0.00, 0.00, 0.00
	Entity's Block location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: com.mrcrayfish.vehicle.client.render.RenderEntityVehicle@63f093a
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:245)
	at com.mrcrayfish.vehicle.client.screen.WorkstationScreen.func_146976_a(WorkstationScreen.java:470)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.render(ContainerScreen.java:73)
	at com.mrcrayfish.vehicle.client.screen.WorkstationScreen.render(WorkstationScreen.java:313)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:365)

-- Screen render details --
Details:
	Screen name: com.mrcrayfish.vehicle.client.screen.WorkstationScreen
	Mouse location: Scaled: (500, 161). Absolute: (1000.000000, 322.000000)
	Screen size: Scaled: (960, 514). Absolute: (1920, 1027). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['CyberGaming225'/95, l='MpServer', x=-431.41, y=70.00, z=-78.62]]
	Chunk stats: Client Chunk Cache: 1369, 982
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 5356531856026262339
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-48,71,0), Chunk: (at 0,4,0 in -3,0; contains blocks -48,0,0 to -33,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 888147 game time, 1000 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1719)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:534)
	at net.minecraft.client.main.Main.main(SourceFile:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$400/1642308093.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.1
	Minecraft Version ID: 1.15.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1358569976 bytes (1295 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.1-30.0.51.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.51.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.1-30.0.51.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.51.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.1-30.0.51.jar fml TRANSFORMATIONSERVICE 
	FML: 30.0
	Forge: net.minecraftforge:30.0.51
	FML Language Providers: 
		javafml@30.0
		minecraft@1
		kotori_scala@2.13.1
	Mod List: 
		forge-1.15.1-30.0.51-client.jar Minecraft {minecraft@1.15.1 DONE}
		obfuscate-0.3.4-1.15.1.jar Obfuscate {obfuscate@0.3.4 DONE}
		LargeFluidTank-15.0.6.jar FluidTank {fluidtank@15.0.6 DONE}
		forge-1.15.1-30.0.51-universal.jar Forge {forge@30.0.51 DONE}
		MrCrayfishs-Furniture-Mod-1.15.2.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		vehicle-0.42.4-mc1.15.1.jar MrCrayfish's Vehicle Mod {vehicle@0.42.4 DONE}
	Launched Version: 1.15.1-forge-30.0.51
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2080/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources (incompatible), vanilla, file/Clarity-1.15
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

My crash report

**Comment by MrCrayfish** [comment]
Use Minecraft 1.15.2
