### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by GENERALWATERS** [MrCrayfish/MrCrayfishVehicleMod#341]
On my server, MC Version 1.12.2, Forge Version 14.23.5.2768, I encounter an odd crash when trying to enter or come near a vehicle
with the error:
        at com.mrcrayfish.vehicle.client.HeldVehicleEvents.patchPlayerRender(HeldVehicleEvents.java:46)
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.onRenderPlayer(HeldVehicleEvents.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1359_HeldVehicleEvents_onRenderPlayer_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)

Now I figured it out the first time that BiblioCraft's Armor stand led to the error so I disabled that block and it worked.
The second time it said Galacticraft, but no block to go off of or ID, so here I am.
In fact, all the vehicles crash upon entering now that I updated your mod to the latest version.
Any idea? Maybe I need to change some sort of Entity ID on one or the other because they're using the same entity or ID? Help would be appreciated because I'm stumped.

EDIT: It's on the 0.44.1 version that causes this issue. I went back one version to 0.44.0 and everything works as it should...

**Comment by MrCrayfish** [comment]
Update to the absolute latest version of Forge for 1.12.2
