### ISSUE TITLE
Crashes on launcher with Optifine 1.15.2 G1 PRE 30 [FIXED Required .minecraft wipe]

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/MrCrayfishVehicleMod#350]
Nothing special just a crash caused by Optifine. Tried a fresh install/reinstalled forge. Heres the crash report 

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 29/09/20 19:51
Description: Initializing game

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/client/renderer/entity/LivingRenderer.func_225623_a_(Lnet/minecraft/entity/LivingEntity;FFLcom/mojang/blaze3d/matrix/MatrixStack;Lnet/minecraft/client/renderer/IRenderTypeBuffer;I)V @747: fload
  Reason:
    Type integer (current frame, locals[14]) is not assignable to float
  Current Frame:
    bci: @747
    flags: { }
    locals: { 'net/minecraft/client/renderer/entity/LivingRenderer', 'net/minecraft/entity/LivingEntity', float, float, 'com/mojang/blaze3d/matrix/MatrixStack', 'net/minecraft/client/renderer/IRenderTypeBuffer', integer, float, float, float, float, float, float, float, integer, integer, integer, 'net/minecraft/client/renderer/RenderType', 'com/mojang/blaze3d/vertex/IVertexBuilder', float, integer, 'net/minecraft/entity/LivingEntity' }
    stack: { 'net/minecraft/client/renderer/entity/model/EntityModel', 'com/mojang/blaze3d/matrix/MatrixStack', 'com/mojang/blaze3d/vertex/IVertexBuilder', integer, integer, float, float, float, float, 'net/minecraft/entity/LivingEntity' }
  Bytecode:
    0x0000000: b200 54b6 005a 9900 33b2 0054 1006 bd00
    0x0000010: 5c59 032b 5359 042a 5359 0525 b800 6253
    0x0000020: 5906 1904 5359 0719 0553 5908 1506 b800
    0x0000030: 6753 b800 6b99 0004 b1b2 006d 9900 082b
    0x0000040: 0cb5 0072 1904 b600 782a b400 322a 2b25
    0x0000050: b600 7cb5 0081 2ab4 0032 2bb6 0084 b500
    0x0000060: 87b2 008b b600 8e99 002e 2ab4 0032 2bb6
    0x0000070: 0084 9900 1f2b b600 92c6 0018 2bb6 0092
    0x0000080: b200 8b03 bd00 5cb8 0096 9900 0704 a700
    0x0000090: 0403 b500 872a b400 322b b600 99b5 009c
    0x00000a0: 252b b400 9f2b b400 a2b8 00a8 3807 252b
    0x00000b0: b400 ab2b b400 aeb8 00a8 3808 1708 1707
    0x00000c0: 6638 092a b400 32b4 0087 9900 6f2b b600
    0x00000d0: 92c1 006f 9900 652b b600 92c0 006f 3a0a
    0x00000e0: 2519 0ab4 009f 190a b400 a2b8 00a8 3807
    0x00000f0: 1708 1707 6638 0917 09b8 00b2 380b 170b
    0x0000100: 12b3 969c 0007 12b3 380b 170b 12b4 959b
    0x0000110: 0007 12b4 380b 1708 170b 6638 0717 0b17
    0x0000120: 0b6a 12b5 959e 000d 1707 170b 12b6 6a62
    0x0000130: 3807 1708 1707 6638 0925 2bb4 00b9 2bb4
    0x0000140: 00bc b800 bf38 0a2b b600 c3b2 00c9 a600
    0x0000150: 362b b600 cd3a 0b19 0bc6 002b 2bb2 00d0
    0x0000160: b600 d412 d566 380c 1904 190b b600 db74
    0x0000170: 8617 0c6a 8d0e 190b b600 de74 8617 0c6a
    0x0000180: 8db6 00e2 2a2b 25b6 00e5 380b 2a2b 1904
    0x0000190: 170b 1707 25b6 00e9 1904 12ea 12ea 0cb6
    0x00001a0: 00ee 2a2b 1904 25b6 00f2 1904 0e14 00f3
    0x00001b0: 0eb6 00e2 0b38 0c0b 380d 2b3a 152a 1915
    0x00001c0: b700 f89a 0040 2bb6 00fb 9900 3925 2bb4
    0x00001d0: 00fe 2bb4 0072 b800 bf38 0c2b b401 012b
    0x00001e0: b400 720c 2566 6a66 380d 2bb6 0099 9900
    0x00001f0: 0b17 0d13 0102 6a38 0d17 0c0c 959e 0006
    0x0000200: 0c38 0c2a b400 322b 170d 170c 25b6 0106
    0x0000210: 2ab4 0032 2b17 0d17 0c17 0b17 0917 0ab6
    0x0000220: 010a b801 0f99 002b 2a2b b501 112a 170d
    0x0000230: b501 132a 170c b501 152a 170b b501 172a
    0x0000240: 1709 b501 192a 170a b501 1b2a 25b5 011d
    0x0000250: b801 2236 0e2a 2bb6 0125 360f 150f 9a00
    0x0000260: 142b b801 2bb4 012f b601 339a 0007 04a7
    0x0000270: 0004 0336 102a 2b15 0f15 10b6 0137 3a11
    0x0000280: 1911 c600 7619 0519 11b9 013d 0200 3a12
    0x0000290: 2a2b 25b6 0140 3813 150e 9900 2d2b b401
    0x00002a0: 449d 000a 2bb4 0147 9e00 0c0c 0b0b 1301
    0x00002b0: 48b8 014e 1713 0b95 9e00 0f17 1317 1317
    0x00002c0: 1313 014f b801 4e2b 1713 b801 5336 142a
    0x00002d0: b400 3219 0419 1215 0615 140c 0c0c 1510
    0x00002e0: 9900 0913 0154 a700 040c 2b17 0e17 0d17
    0x00002f0: 0c17 0a17 0bb8 015a 2bb6 015d 9a00 3e2a
    0x0000300: b400 30b9 0161 0100 3a12 1912 b901 6601
    0x0000310: 0099 0029 1912 b901 6a01 00c0 016c 3a13
    0x0000320: 1913 1904 1905 1506 2b17 0d17 0c25 170b
    0x0000330: 1709 170a b601 70a7 ffd3 b801 2299 000a
    0x0000340: 0b0b 0b0b b801 4eb8 010f 9900 082a 01b5
    0x0000350: 0111 1904 b601 732a 2b24 2519 0419 0515
    0x0000360: 06b7 0176 b201 79b6 005a 9900 30b2 0179
    0x0000370: 1006 bd00 5c59 032b 5359 042a 5359 0525
    0x0000380: b800 6253 5906 1904 5359 0719 0553 5908
    0x0000390: 1506 b800 6753 b800 6b57 b1            
  Stackmap Table:
    same_frame(@57)
    same_frame(@68)
    same_locals_1_stack_item_extended(@145,Object[#126])
    full_frame(@146,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#313],Integer},{Object[#126],Integer})
    same_frame(@149)
    full_frame(@266,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#313],Integer,Float,Float,Float,Object[#111],Float},{})
    same_frame(@278)
    same_frame(@306)
    chop_frame(@313,2)
    append_frame(@388,Float)
    full_frame(@505,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#313],Integer,Float,Float,Float,Float,Float,Float,Float,Top,Top,Top,Top,Top,Top,Top,Object[#111]},{})
    same_frame(@515)
    same_frame_extended(@592)
    full_frame(@626,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#313],Integer,Float,Float,Float,Float,Float,Float,Float,Integer,Integer,Top,Top,Top,Top,Top,Object[#111]},{})
    same_locals_1_stack_item_frame(@627,Integer)
    full_frame(@683,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#313],Integer,Float,Float,Float,Float,Float,Float,Float,Integer,Integer,Integer,Object[#409],Object[#411],Float,Top,Object[#111]},{})
    same_frame(@692)
    same_frame(@711)
    full_frame(@745,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#313],Integer,Float,Float,Float,Float,Float,Float,Float,Integer,Integer,Integer,Object[#409],Object[#411],Float,Integer,Object[#111]},{Object[#126],Object[#116],Object[#411],Integer,Integer,Float,Float,Float})
    full_frame(@746,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#313],Integer,Float,Float,Float,Float,Float,Float,Float,Integer,Integer,Integer,Object[#409],Object[#411],Float,Integer,Object[#111]},{Object[#126],Object[#116],Object[#411],Integer,Integer,Float,Float,Float,Float})
    full_frame(@760,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#313],Integer,Float,Float,Float,Float,Float,Float,Float,Integer,Integer,Integer,Object[#409],Top,Top,Top,Object[#111]},{})
    full_frame(@778,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#313],Integer,Float,Float,Float,Float,Float,Float,Float,Integer,Integer,Integer,Object[#409],Object[#355],Top,Top,Object[#111]},{})
    full_frame(@826,{Object[#2],Object[#111],Float,Float,Object[#116],Object[#313],Integer,Float,Float,Float,Float,Float,Float,Float,Integer,Integer,Integer,Object[#409],Top,Top,Top,Object[#111]},{})
    same_frame(@839)
    same_frame(@850)
    same_frame_extended(@922)

	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229097_a_(EntityRendererManager.java:103) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:211) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.43.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$453/1774897456.call(Unknown Source) [forge-1.15.2-31.2.43.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229097_a_(EntityRendererManager.java:103)
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:211)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$453/1774897456.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2660462664 bytes (2537 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.43.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.43.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.43.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.43.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre30%20(1).jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.43.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.15.2-0.1.29%20(2).jar FakeOptiFine TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.4%20(2).jar mixinbootstrap TRANSFORMATIONSERVICE 
		/OptiForge-MC1.15.2-0.1.29%20(2).jar optiforge TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.4%20(2).jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.4%20(2).jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.43
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.43-client.jar Minecraft {minecraft@1.15.2 COMMON_SETUP}
		OptiForge-MC1.15.2-0.1.29 (2).jar OptiForge {optiforge@0.1.29 COMMON_SETUP}
		obfuscate-0.5.0-1.15.2.jar Obfuscate {obfuscate@0.5.0 COMMON_SETUP}
		forge-1.15.2-31.2.43-universal.jar Forge {forge@31.2.43 COMMON_SETUP}
		vehicle-mod-0.44.1-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.44.1 COMMON_SETUP}
	Launched Version: 1.15.2-forge-31.2.43
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.55, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre30
	OptiFine Build: 20200622-083032
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.281 Lite.zip
	OpenGlVersion: 4.6.0 NVIDIA 456.55
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by ShadowBlack27** [comment]
optifine is incompatibal

**Comment by ShadowBlack27** [comment]
Mr.crayfish said it was
