### ISSUE TITLE
I am getting errors for every item in the mod

### ISSUE THREAD

**Issue by RedstonedLife** [MrCrayfish/MrCrayfishVehicleMod#388]
Technical Details:
I'm running a `Mohist Server` using `Mohist_1.16.4` build `#195`
`Mohist_1.16.4-195` runs `Forge 1.16.4` while implementing `Spigot/Bukkit` api
for the use of plugins.

Mod list (Currently installed):
* `BlockFront-1.16.4.0.0.2.37a-RELEASE ` (Can be viewed [here](https://www.curseforge.com/minecraft/mc-mods/blockfront-world-war-ii) )
* `Furniture-7.0.0-pre19-1.16.3` (Can be viewed [here](https://mrcrayfish.com/mods?id=cfm) )
* `MrCrayfishs-Vehicle-Mod-1.16.4` (Can be viewed [here](https://mrcrayfish.com/mods?id=vehicle) )
* `obfuscate-0.5.1-1.16.3` (Can be viewed [here](https://mrcrayfish.com/mods?id=obfuscate) )
* `simpleplanes-1.16.3-3.2.0.3` (Can be viewed [here](https://www.curseforge.com/minecraft/mc-mods/simple-planes) )
* `worldedit-forge-mc1.16.3-7.2.1-dist.jar` (Can be viewed [here](https://www.curseforge.com/minecraft/mc-mods/worldedit) )

Raw Text Stack Trace of 2 errors (I won't list all, because the others are json related and there is a bunch of them)

First Error:
>[13:27:13 ERROR]: No data fixer registered for vehicle:atv
[13:27:13 ERROR]: No data fixer registered for vehicle:dune_buggy
[13:27:13 INFO]: [BlockFront] Registering server-side forge events...
[13:27:13 ERROR]: No data fixer registered for vehicle:go_kart
[13:27:13 ERROR]: No data fixer registered for vehicle:shopping_cart
[13:27:13 ERROR]: No data fixer registered for vehicle:mini_bike
[13:27:13 INFO]: [BlockFront] Successfully registered forge events!
[13:27:13 ERROR]: No data fixer registered for vehicle:bumper_car
[13:27:13 ERROR]: No data fixer registered for vehicle:jet_ski
[13:27:13 ERROR]: No data fixer registered for vehicle:speed_boat
[13:27:13 ERROR]: No data fixer registered for vehicle:aluminum_boat
[13:27:13 ERROR]: No data fixer registered for vehicle:smart_car
[13:27:13 ERROR]: No data fixer registered for vehicle:lawn_mower
[13:27:13 ERROR]: No data fixer registered for vehicle:moped
[13:27:13 ERROR]: No data fixer registered for vehicle:sports_plane
[13:27:13 ERROR]: No data fixer registered for vehicle:golf_cart
[13:27:14 ERROR]: No data fixer registered for vehicle:off_roader
[13:27:14 ERROR]: No data fixer registered for vehicle:tractor
[13:27:14 ERROR]: No data fixer registered for vehicle:mini_bus
[13:27:14 ERROR]: No data fixer registered for vehicle:dirt_bike
[13:27:14 ERROR]: No data fixer registered for vehicle:vehicle_trailer
[13:27:14 ERROR]: No data fixer registered for vehicle:storage_trailer
[13:27:14 ERROR]: No data fixer registered for vehicle:fluid_trailer
[13:27:14 ERROR]: No data fixer registered for vehicle:seeder
[13:27:14 ERROR]: No data fixer registered for vehicle:fertilizer
[13:27:14 ERROR]: No data fixer registered for vehicle:couch
[13:27:14 ERROR]: No data fixer registered for vehicle:bath
[13:27:14 ERROR]: No data fixer registered for vehicle:sofacopter
[13:27:14 ERROR]: No data fixer registered for jack
[13:27:15 ERROR]: No data fixer registered for cfm:seat

Second Error:
>[13:27:25 ERROR]: Parsing error loading recipe cfm:craft_sofa
com.google.gson.JsonSyntaxException: Invalid vehicle entity: vehicle:sofa
        at com.mrcrayfish.vehicle.crafting.VehicleRecipeSerializer.read(VehicleRecipeSerializer.java:48) ~[vehicle:0.45.2-1.16.3] {re:classloading}
        at com.mrcrayfish.vehicle.crafting.VehicleRecipeSerializer.func_199425_a_(VehicleRecipeSerializer.java:23) ~[vehicle:0.45.2-1.16.3] {re:classloading}
        at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:154) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:60) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:37) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_271] {}
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_271] {}
        at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
        at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_271] {}
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_271] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_271] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_271] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_271] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_271] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_271] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_271] {}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_271] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_271] {}
        
Second error I get for all items.

Is there a way to fix this?
@MrCrayfish 
This also results in the vehicles not spawning upon putting down the `Vehicle Crate`

**Comment by RedstonedLife** [comment]
I cannot spawn the vehicles through the Vehicle Crate, the item looses all NBT tags when placed and or given through creative.
I did successfully spawn the vehicles through `/summon` the work well. and very good, Just annoying I have to use `/summon` instead of just crafting them, It removes the fun I guess

**Comment by MrCrayfish** [comment]
Can you try without using a Mohist server? As stated on their GitHub repo, there are many compatibility issues with mods. 
The warnings posted are nothing to worry about. Data Fixers are simply a system that Mojang implemented to help update old minecrafts saves to newer versions. The second error can be fixed though.

**Comment by RedstonedLife** [comment]
Okay, so I attempted to run with with regular forge, not mohist,
I am still getting some `Data Fixers` error and `Parsing error loading recipe vehicle:item-name`
But this time the Vehicle Crates do not loose their NBT tags and do the animations.
But the issue is, I need to run the server with plugins, hence why I used mohist.

**Comment by MrCrayfish** [comment]
You'll have to bring it up to devs of Mohist. NBT for the Vehicle Crates uses vanilla's "BlockEntityTag", so I have no idea why it wouldn't work.

**Comment by RedstonedLife** [comment]
Will do, I'll create an issue on the mohist repo and let them know.
Thanks for the help, you're a life saver.
