### ISSUE TITLE
fuel not working in servers

### ISSUE THREAD

**Issue by kreytzxd** [MrCrayfish/MrCrayfishVehicleMod#408]
whenever i try to fuel up my bike or something it doesnt work
when im on servers
but when im on single player it does work

**Comment by Darkona** [comment]
Adding to this>
In Minecraft 1.12.2, attempting to fill the tank of a bike **using the fuel pump**, **either of the jerry cans**, and as an stopped bike on ground or on the piston thing that raises it. The game CTD's with a NullPointerException from rendering:

Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at com.mrcrayfish.vehicle.client.render.RenderVehicleWrapper.renderFuelPort(RenderVehicleWrapper.java:182)
	at com.mrcrayfish.vehicle.client.render.RenderMotorcycleWrapper.render(RenderMotorcycleWrapper.java:101)
	at com.mrcrayfish.vehicle.client.render.RenderMotorcycleWrapper.render(RenderMotorcycleWrapper.java:13)
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.doRender(RenderEntityVehicle.java:61)
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_76986_a(RenderEntityVehicle.java:19)
	at net.minecraft.client.renderer.entity.RenderManager.laggoggles_trueRender(RenderManager.java:384)
	at com.github.terminatornl.laggoggles.tickcentral.RenderManagerAdapter.redirectRenderEntity(RenderManagerAdapter.java:18)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.wildbamaboy.crashtomainmenu.asm.ASMHooks.onMinecraftRun(ASMHooks.java:56)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

This crashes the client as is a rendering issue, but not the server. Happens with the bike, not sure if it happens with other vehicles. I was able to refill a motor boat and an aluminium boat, so the issue is not present on all vehicles. This is a gamebreaking issue so if the 1.12.2 version is in maintenance mode, I would suggest to take a look at it. This crash is present while playing on a server, as the comment above states.
