### ISSUE TITLE
Game crashes when I open my inventory and click on the tab

### ISSUE THREAD

**Issue by bluebell3390** [MrCrayfish/MrCrayfishVehicleMod#552]
--- Minecraft Crash Report ----

WARNING: coremods are present:
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 6/17/23 10:44 AM
Description: Rendering entity in world

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.getPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.patchPlayerRender(HeldVehicleEvents.java:46)
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.onRenderPlayer(HeldVehicleEvents.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_83_HeldVehicleEvents_onRenderPlayer_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:128)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:802)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.patchPlayerRender(HeldVehicleEvents.java:46)
	at com.mrcrayfish.vehicle.client.HeldVehicleEvents.onRenderPlayer(HeldVehicleEvents.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_83_HeldVehicleEvents_onRenderPlayer_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)

-- Entity being rendered --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 1503
	Entity Name: Candy1976
	Entity's Exact location: -249.63, 83.00, 256.13
	Entity's Block location: World: (-250,83,256), Chunk: (at 6,5,0 in -16,16; contains blocks -256,0,256 to -241,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderPlayer@4bada65d
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:128)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:802)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (351, 228). Absolute: (1053, 214)
	Screen size: Scaled: (534, 300). Absolute: (1600, 900). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Candy1976'/1503, l='MpServer', x=-249.63, y=83.00, z=256.13]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-256,64,252), Chunk: (at 0,4,12 in -16,15; contains blocks -256,0,240 to -241,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 702 game time, 702 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 87 total; [EntityCow['Cow'/896, l='MpServer', x=-247.21, y=71.00, z=205.39], EntityCow['Cow'/897, l='MpServer', x=-231.15, y=76.00, z=232.53], EntityCreeper['Creeper'/898, l='MpServer', x=-239.50, y=30.00, z=266.50], EntityItem['item.item.seeds'/899, l='MpServer', x=-238.24, y=62.00, z=317.34], EntityCow['Cow'/524, l='MpServer', x=-296.50, y=69.00, z=227.50], EntityCow['Cow'/525, l='MpServer', x=-294.23, y=68.00, z=229.57], EntityCow['Cow'/526, l='MpServer', x=-298.50, y=69.00, z=227.50], EntityCow['Cow'/527, l='MpServer', x=-299.54, y=69.00, z=229.60], EntitySkeleton['Skeleton'/667, l='MpServer', x=-245.50, y=50.00, z=187.50], EntityZombie['Zombie'/668, l='MpServer', x=-253.50, y=47.00, z=206.50], EntityCow['Cow'/669, l='MpServer', x=-244.50, y=71.00, z=207.50], EntityCow['Cow'/670, l='MpServer', x=-248.42, y=71.00, z=216.23], EntityCreeper['Creeper'/671, l='MpServer', x=-251.50, y=47.00, z=209.50], EntityCow['Cow'/672, l='MpServer', x=-241.50, y=71.00, z=211.50], EntityZombie['Zombie'/673, l='MpServer', x=-257.19, y=30.00, z=256.50], EntityCreeper['Creeper'/674, l='MpServer', x=-254.50, y=28.00, z=262.50], EntityZombie['Zombie'/675, l='MpServer', x=-254.48, y=27.00, z=281.28], EntityCow['Cow'/931, l='MpServer', x=-211.50, y=68.00, z=207.50], EntityBat['Bat'/676, l='MpServer', x=-245.46, y=29.17, z=275.43], EntityCow['Cow'/932, l='MpServer', x=-213.47, y=69.00, z=225.79], EntitySkeleton['Skeleton'/549, l='MpServer', x=-285.50, y=14.00, z=198.50], EntityZombie['Zombie'/677, l='MpServer', x=-244.51, y=42.00, z=293.24], EntityCow['Cow'/933, l='MpServer', x=-213.50, y=67.00, z=208.50], EntityEnderman['Enderman'/550, l='MpServer', x=-272.42, y=32.00, z=283.57], EntityEnderman['Enderman'/678, l='MpServer', x=-246.51, y=41.00, z=291.63], EntityCow['Cow'/934, l='MpServer', x=-209.50, y=68.00, z=210.50], EntityEnderman['Enderman'/551, l='MpServer', x=-272.14, y=31.00, z=288.38], EntityBat['Bat'/679, l='MpServer', x=-245.46, y=41.63, z=293.62], EntityCow['Cow'/935, l='MpServer', x=-208.46, y=68.00, z=210.85], EntityEnderman['Enderman'/552, l='MpServer', x=-267.46, y=30.00, z=324.51], EntityCow['Cow'/936, l='MpServer', x=-223.50, y=73.00, z=232.50], EntityCreeper['Creeper'/553, l='MpServer', x=-282.50, y=35.00, z=306.50], EntityCow['Cow'/937, l='MpServer', x=-223.50, y=73.00, z=234.50], EntityCreeper['Creeper'/554, l='MpServer', x=-283.50, y=35.00, z=306.50], EntityCow['Cow'/938, l='MpServer', x=-228.20, y=67.00, z=238.50], EntityCow['Cow'/555, l='MpServer', x=-281.08, y=68.00, z=324.03], EntitySheep['Sheep'/939, l='MpServer', x=-210.45, y=69.00, z=332.45], EntityCow['Cow'/556, l='MpServer', x=-280.48, y=68.00, z=328.15], EntitySheep['Sheep'/940, l='MpServer', x=-211.67, y=68.00, z=333.48], EntityCow['Cow'/557, l='MpServer', x=-285.50, y=72.00, z=326.50], EntityRabbit['Rabbit'/941, l='MpServer', x=-210.83, y=69.00, z=333.38], EntityCow['Cow'/558, l='MpServer', x=-285.50, y=72.00, z=326.50], EntityRabbit['Rabbit'/942, l='MpServer', x=-209.50, y=69.00, z=335.50], EntityCow['Cow'/953, l='MpServer', x=-203.50, y=70.00, z=218.50], EntityBat['Bat'/570, l='MpServer', x=-274.25, y=12.11, z=201.25], EntityCow['Cow'/954, l='MpServer', x=-213.47, y=67.00, z=215.15], EntityZombie['Zombie'/571, l='MpServer', x=-259.50, y=29.00, z=260.50], EntityCow['Cow'/955, l='MpServer', x=-200.53, y=68.00, z=218.45], EntityZombie['Zombie'/572, l='MpServer', x=-256.50, y=29.00, z=259.50], EntityZombie['Zombie'/956, l='MpServer', x=-207.50, y=27.00, z=279.50], EntityCreeper['Creeper'/573, l='MpServer', x=-267.50, y=35.00, z=266.50], EntityZombie['Zombie'/957, l='MpServer', x=-203.67, y=27.00, z=277.77], EntitySkeleton['Skeleton'/574, l='MpServer', x=-266.27, y=32.00, z=265.50], EntityChicken['Chicken'/958, l='MpServer', x=-205.50, y=71.00, z=335.50], EntityBat['Bat'/575, l='MpServer', x=-259.25, y=30.66, z=288.53], EntitySheep['Sheep'/959, l='MpServer', x=-206.48, y=71.00, z=332.74], EntitySkeleton['Skeleton'/576, l='MpServer', x=-259.50, y=33.00, z=283.50], EntityChicken['Chicken'/960, l='MpServer', x=-209.19, y=71.00, z=324.58], EntityZombie['Zombie'/577, l='MpServer', x=-257.50, y=33.00, z=281.50], EntityZombie['Zombie'/578, l='MpServer', x=-256.50, y=33.00, z=277.50], EntityZombie['Zombie'/579, l='MpServer', x=-258.50, y=33.00, z=280.50], EntitySpider['Spider'/580, l='MpServer', x=-257.50, y=33.00, z=283.50], EntityEnderman['Enderman'/581, l='MpServer', x=-262.50, y=34.00, z=283.70], EntityEnderman['Enderman'/582, l='MpServer', x=-269.56, y=31.00, z=290.54], EntitySkeleton['Skeleton'/583, l='MpServer', x=-271.50, y=54.00, z=297.50], EntityCreeper['Creeper'/584, l='MpServer', x=-257.50, y=20.00, z=306.50], EntitySkeleton['Skeleton'/585, l='MpServer', x=-265.70, y=27.00, z=319.70], EntityEnderman['Enderman'/586, l='MpServer', x=-270.61, y=23.00, z=312.50], EntityZombieVillager['Zombie Villager'/587, l='MpServer', x=-258.51, y=33.00, z=308.80], EntityZombieVillager['Zombie Villager'/588, l='MpServer', x=-268.46, y=34.00, z=319.25], EntitySkeleton['Skeleton'/592, l='MpServer', x=-258.72, y=51.00, z=333.26], EntityBat['Bat'/469, l='MpServer', x=-321.38, y=18.02, z=247.55], EntitySpider['Spider'/471, l='MpServer', x=-327.50, y=46.00, z=325.50], EntityCow['Cow'/988, l='MpServer', x=-187.50, y=71.00, z=218.50], EntityCow['Cow'/989, l='MpServer', x=-188.50, y=70.00, z=220.50], EntityCow['Cow'/990, l='MpServer', x=-186.50, y=65.00, z=222.50], EntityCow['Cow'/991, l='MpServer', x=-186.50, y=63.00, z=224.50], EntityBat['Bat'/992, l='MpServer', x=-175.54, y=35.10, z=233.11], EntityCreeper['Creeper'/481, l='MpServer', x=-319.50, y=34.00, z=241.50], EntityBat['Bat'/993, l='MpServer', x=-182.13, y=38.39, z=245.37], EntityZombie['Zombie'/482, l='MpServer', x=-318.50, y=34.00, z=246.50], EntitySkeleton['Skeleton'/483, l='MpServer', x=-318.50, y=65.00, z=279.50], EntityBat['Bat'/484, l='MpServer', x=-308.53, y=45.03, z=328.75], EntityRabbit['Rabbit'/1134, l='MpServer', x=-174.00, y=63.94, z=290.51], EntityBat['Bat'/1523, l='MpServer', x=-238.92, y=26.02, z=327.68], EntityPlayerSP['Candy1976'/1503, l='MpServer', x=-249.63, y=83.00, z=256.13], EntityCreeper['Creeper'/1140, l='MpServer', x=-171.50, y=16.00, z=320.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 930658752 bytes (887 MB) / 1744830464 bytes (1664 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID             | Version      | Source                                        | Signature                                |
	|:--------- |:-------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft      | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp            | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge          | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | obfuscate      | 0.2.6        | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | codechickenlib | 3.2.3.358    | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | jei            | 4.14.4.267   | jei_1.12.2-4.14.4.267.jar                     | None                                     |
	| UCHIJAAAA | nei            | 2.4.3        | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | vehicle        | 0.44.1       | vehicle-mod-0.44.1-1.12.2.jar                 | None                                     |

	Loaded coremods (and transformers): 
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7926' Renderer: 'Intel(R) Iris(R) Plus Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Intel(R) Iris(R) Plus Graphics GL version 4.6.0 - Build 26.20.100.7926, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Modern HD 1.12.1.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz

**Comment by bluebell3390** [comment]
Game crashes when I open my inventory and click a tab......I removed some mods to pinpoint the problem but it still does it.

**Comment by QboiDev** [comment]
Looks like Forge is missing some method/function in `net.minecraftforge.fml.common.ObfuscationReflectionHelper` which is kinda weird.
Try to update Forge I also see that you use an older version.
