### ISSUE TITLE
Crash entity plane v0.28 and 0.29 too

### ISSUE THREAD

**Issue by ipv2007** [MrCrayfish/MrCrayfishVehicleMod#60]
Time: 11/4/18 3:28 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
	at com.mrcrayfish.vehicle.entity.EntityPlane.getFlapDirection(EntityPlane.java:233)
	at com.mrcrayfish.vehicle.entity.EntityPlane.updateLift(EntityPlane.java:191)
	at com.mrcrayfish.vehicle.entity.EntityPlane.updateVehicleMotion(EntityPlane.java:55)
	at com.mrcrayfish.vehicle.entity.EntityPoweredVehicle.onUpdateVehicle(EntityPoweredVehicle.java:310)
	at com.mrcrayfish.vehicle.entity.EntityVehicle.func_70071_h_(EntityVehicle.java:202)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1846)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Siavel** [comment]
https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/21

**Comment by MrCrayfish** [comment]
Duplicate issue
