### ISSUE TITLE
A couple bug(s) and a crash. (a few issues/observations)

### ISSUE THREAD

**Issue by SniperHauss89** [MrCrayfish/MrCrayfishVehicleMod#84]
Hello, I just thought I would post a couple bugs(?) I ran into as well as an occurrence where a series of events lead to a recurring server side crash that made it so I had to load a world backup.

Forge version: Recommended - 1.12.2 - 14.23.5.2768
Mod version: 0.33.0

1. The simple bug: When you mine a fluid mixer to pick it up it drops two of them not one so obviously you can see the issue lol.
2. Not sure if it's a bug but the fluid pipes didn't seem to want to connect to the fluid mixer and the pipe was also connecting to the grass below as well.
3. I made a lawnmower and a single storage trailer and had connected then. I then start messing around a little and accidently picked up the mower and then the trailer and as I put them down I looked toward the trailer and unintentionally right click the grass I believe and all the sudden the server went into a crash loop cycle. error log: https://pastebin.com/EgyhdJR2

**Comment by MrCrayfish** [comment]
Can I get an update on this issue? Does issue 1 & 3 this happen in the latest version of the mod?

**Comment by koolio88** [comment]
crayfish i'm having an issue with the storage trailer on the game everytime I tied to spawn the trailer in game the freezes and than it ctd but when i spawn the vehicle trailer there is no problem the crash report always says something to the effect of the of render

**Comment by koolio88** [comment]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 1/25/20 10:28 PM
Description: Rendering Block Entity

java.lang.NoSuchMethodError: net.minecraft.item.Item.getTileEntityItemStackRenderer()Lnet/minecraft/client/renderer/tileentity/ItemStackTileEntityRenderer;
	at com.mrcrayfish.vehicle.util.RenderUtil.renderModel(RenderUtil.java:138) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:52) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:21) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.RenderVehicleWrapper.render(RenderVehicleWrapper.java:68) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_225623_a_(RenderEntityVehicle.java:46) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_225623_a_(RenderEntityVehicle.java:17) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.tileentity.VehicleCrateRenderer.func_225616_a_(VehicleCrateRenderer.java:125) ~[?:0.42.4-1.15.1] {re:classloading}
	at com.mrcrayfish.vehicle.client.render.tileentity.VehicleCrateRenderer.func_225616_a_(VehicleCrateRenderer.java:28) ~[?:0.42.4-1.15.1] {re:classloading}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:100) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$func_228850_a_$0(TileEntityRendererDispatcher.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$5113/1754596529.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:124) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:83) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:980) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:601) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:423) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:882) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:520) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:202) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.1-30.0.51.jar:30.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$411/1346197173.call(Unknown Source) [forge-1.15.1-30.0.51.jar:30.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mrcrayfish.vehicle.util.RenderUtil.renderModel(RenderUtil.java:138)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:52)
	at com.mrcrayfish.vehicle.client.render.vehicle.RenderStorageTrailer.render(RenderStorageTrailer.java:21)
	at com.mrcrayfish.vehicle.client.render.RenderVehicleWrapper.render(RenderVehicleWrapper.java:68)
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_225623_a_(RenderEntityVehicle.java:46)
	at com.mrcrayfish.vehicle.client.render.RenderEntityVehicle.func_225623_a_(RenderEntityVehicle.java:17)
	at com.mrcrayfish.vehicle.client.render.tileentity.VehicleCrateRenderer.func_225616_a_(VehicleCrateRenderer.java:125)
	at com.mrcrayfish.vehicle.client.render.tileentity.VehicleCrateRenderer.func_225616_a_(VehicleCrateRenderer.java:28)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$func_228850_a_$0(TileEntityRendererDispatcher.java:84)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$5113/1754596529.run(Unknown Source)

-- Block Entity Details --
Details:
	Name: vehicle:vehicle_crate // com.mrcrayfish.vehicle.tileentity.VehicleCrateTileEntity
	Block: Block{vehicle:vehicle_crate}[facing=east]
	Block location: World: (-45,4,-222), Chunk: (at 3,0,2 in -3,-14; contains blocks -48,0,-224 to -33,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Block: Block{vehicle:vehicle_crate}[facing=east]
	Block location: World: (-45,4,-222), Chunk: (at 3,0,2 in -3,-14; contains blocks -48,0,-224 to -33,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:124)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:83)
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:980)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:601)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Junit2011'/144, l='MpServer', x=-47.50, y=4.00, z=-219.50]]
	Chunk stats: Client Chunk Cache: 361, 225
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 2918194269761290109
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-48,4,-176), Chunk: (at 0,0,0 in -3,-11; contains blocks -48,0,-176 to -33,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 7472 game time, 1019 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1719)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:534)
	at net.minecraft.client.main.Main.main(SourceFile:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$411/1346197173.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
