### ISSUE TITLE
Client crashed when "allow-flight" is set to true on latest Forge server build

### ISSUE THREAD

**Issue by FujiMakoto** [MrCrayfish/MrCrayfishVehicleMod#91]
Crash report:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 1/17/19 3:08 AM
Description: Ticking entity

java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
	at com.mrcrayfish.vehicle.entity.EntityPlane.getFlapDirection(EntityPlane.java:233)
	at com.mrcrayfish.vehicle.entity.EntityPlane.updateLift(EntityPlane.java:191)
	at com.mrcrayfish.vehicle.entity.EntityPlane.updateVehicleMotion(EntityPlane.java:55)
	at com.mrcrayfish.vehicle.entity.EntityPoweredVehicle.onUpdateVehicle(EntityPoweredVehicle.java:336)
	at com.mrcrayfish.vehicle.entity.EntityVehicle.func_70071_h_(EntityVehicle.java:285)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1846)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.vehicle.entity.EntityPlane.getFlapDirection(EntityPlane.java:233)
	at com.mrcrayfish.vehicle.entity.EntityPlane.updateLift(EntityPlane.java:191)
	at com.mrcrayfish.vehicle.entity.EntityPlane.updateVehicleMotion(EntityPlane.java:55)
	at com.mrcrayfish.vehicle.entity.EntityPoweredVehicle.onUpdateVehicle(EntityPoweredVehicle.java:336)
	at com.mrcrayfish.vehicle.entity.EntityVehicle.func_70071_h_(EntityVehicle.java:285)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: vehicle:sports_plane (com.mrcrayfish.vehicle.entity.vehicle.EntitySportsPlane)
	Entity ID: 217
	Entity Name: Sports Plane
	Entity's Exact location: 119.55, 64.00, 262.89
	Entity's Block location: World: (119,64,262), Chunk: (at 7,4,6 in 7,16; contains blocks 112,0,256 to 127,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TheMakoto'/312, l='MpServer', x=117.91, y=64.00, z=265.42]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-16,64,240), Chunk: (at 0,4,0 in -1,15; contains blocks -16,0,240 to -1,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 13987610 game time, 14291215 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 92 total; [EntityRoosterRhodeIslandRed['Rhode Island Red Rooster'/130, l='MpServer', x=59.50, y=27.00, z=222.50], EntityZombie['Zombie'/515, l='MpServer', x=193.50, y=44.00, z=241.50], EntityZombie['Zombie'/132, l='MpServer', x=56.51, y=28.00, z=224.20], EntityZombie['Zombie'/516, l='MpServer', x=194.50, y=44.00, z=249.50], EntitySkeleton['Skeleton'/261, l='MpServer', x=164.50, y=33.00, z=224.50], EntitySkeleton['Skeleton'/133, l='MpServer', x=61.50, y=14.00, z=297.50], EntityCreeper['Creeper'/262, l='MpServer', x=175.50, y=34.00, z=225.50], EntitySpider['Spider'/134, l='MpServer', x=62.50, y=14.00, z=296.50], EntityFenceFastener['Fastener'/263, l='MpServer', x=160.50, y=67.50, z=268.50], EntityFenceFastener['Fastener'/264, l='MpServer', x=160.50, y=67.50, z=281.50], EntityHamster['Hamster'/265, l='MpServer', x=173.23, y=64.00, z=286.57], EntityFenceFastener['Fastener'/266, l='MpServer', x=171.50, y=65.50, z=292.50], EntityFenceFastener['Fastener'/267, l='MpServer', x=171.50, y=65.50, z=299.50], EntityDoeFainting['Fainting Doe'/268, l='MpServer', x=162.89, y=65.00, z=299.32], EntityZombie['Zombie'/524, l='MpServer', x=197.50, y=48.00, z=300.79], EntityRamFriesian['Friesian Ram'/269, l='MpServer', x=162.16, y=66.00, z=295.54], EntityPlayerSP['TheMakoto'/312, l='MpServer', x=117.91, y=64.00, z=265.42], EntityDoeAngora['Angora Doe'/270, l='MpServer', x=162.18, y=66.00, z=297.05], EntityCreeper['Creeper'/142, l='MpServer', x=65.50, y=17.00, z=185.50], EntitySkeleton['Skeleton'/271, l='MpServer', x=163.50, y=38.00, z=308.50], EntityRabbitBuckLop['Lop Buck'/145, l='MpServer', x=78.77, y=72.00, z=216.94], EntityHenRhodeIslandRed['Rhode Island Red Hen'/146, l='MpServer', x=66.75, y=62.05, z=268.75], EntitySkeleton['Skeleton'/147, l='MpServer', x=67.50, y=29.00, z=300.50], EntityBat['Bat'/148, l='MpServer', x=67.82, y=18.40, z=317.43], EntitySkeleton['Skeleton'/149, l='MpServer', x=68.50, y=20.00, z=323.50], EntityZombie['Zombie'/150, l='MpServer', x=74.50, y=23.00, z=344.50], EntityZombie['Zombie'/279, l='MpServer', x=189.50, y=35.00, z=199.50], EntitySkeleton['Skeleton'/280, l='MpServer', x=185.54, y=55.00, z=206.26], EntityCreeper['Creeper'/281, l='MpServer', x=186.50, y=55.00, z=205.50], EntitySkeleton['Skeleton'/282, l='MpServer', x=187.50, y=55.00, z=200.73], EntityBat['Bat'/283, l='MpServer', x=188.40, y=34.21, z=211.95], EntityBat['Bat'/284, l='MpServer', x=182.75, y=29.87, z=233.51], EntitySkeleton['Skeleton'/285, l='MpServer', x=177.12, y=41.00, z=239.57], EntityBat['Bat'/541, l='MpServer', x=155.50, y=44.00, z=300.50], EntityWitch['Witch'/286, l='MpServer', x=184.50, y=44.00, z=231.50], EntityBat['Bat'/287, l='MpServer', x=184.57, y=39.53, z=236.94], EntityZombie['Zombie'/288, l='MpServer', x=187.50, y=44.00, z=242.50], EntityRamJacob['Jacob Ram'/161, l='MpServer', x=95.96, y=64.00, z=222.05], EntityMareDraftHorse['Draft Horse Mare'/162, l='MpServer', x=90.61, y=63.00, z=239.44], EntityBat['Bat'/290, l='MpServer', x=190.37, y=35.99, z=256.75], EntityHenRhodeIslandRed['Rhode Island Red Hen'/163, l='MpServer', x=88.01, y=62.63, z=244.22], EntityFenceFastener['Fastener'/291, l='MpServer', x=185.50, y=67.50, z=268.50], EntityRabbitBuckCottontail['Cottontail Buck'/164, l='MpServer', x=88.75, y=62.37, z=244.73], EntityFenceFastener['Fastener'/292, l='MpServer', x=185.50, y=67.50, z=285.50], EntityFoalDraftHorse['Draft Horse Foal'/165, l='MpServer', x=97.48, y=63.00, z=240.50], EntityRoosterRhodeIslandRed['Rhode Island Red Rooster'/166, l='MpServer', x=94.45, y=45.00, z=257.61], EntityFenceFastener['Fastener'/294, l='MpServer', x=182.50, y=65.50, z=292.50], EntityCalfFriesian['Friesian Calf'/167, l='MpServer', x=83.64, y=64.00, z=263.49], EntityFenceFastener['Fastener'/295, l='MpServer', x=182.50, y=65.50, z=299.50], EntityHenRhodeIslandRed['Rhode Island Red Hen'/168, l='MpServer', x=81.55, y=15.00, z=309.11], EntityBat['Bat'/169, l='MpServer', x=86.54, y=24.76, z=325.73], EntityCreeper['Creeper'/297, l='MpServer', x=189.21, y=49.00, z=316.47], EntityBat['Bat'/170, l='MpServer', x=110.59, y=24.74, z=317.82], EntityZombie['Zombie'/298, l='MpServer', x=178.96, y=18.00, z=333.40], EntityZombie['Zombie'/171, l='MpServer', x=83.50, y=56.00, z=304.50], EntityZombieVillager['Zombie Villager'/172, l='MpServer', x=82.50, y=56.00, z=304.50], EntitySkeleton['Skeleton'/174, l='MpServer', x=87.77, y=22.00, z=328.50], EntitySkeleton['Skeleton'/175, l='MpServer', x=87.51, y=17.00, z=326.71], EntityBat['Bat'/176, l='MpServer', x=87.01, y=25.01, z=323.07], EntityBat['Bat'/177, l='MpServer', x=92.58, y=25.22, z=315.47], EntityZombie['Zombie'/203, l='MpServer', x=99.50, y=25.00, z=283.50], EntityBat['Bat'/204, l='MpServer', x=111.75, y=38.10, z=318.75], EntityWitch['Witch'/205, l='MpServer', x=105.50, y=19.00, z=334.50], EntityBat['Bat'/206, l='MpServer', x=118.86, y=14.03, z=326.97], EntityCowFriesian['Friesian Cow'/216, l='MpServer', x=117.00, y=66.00, z=241.29], EntitySportsPlane['Sports Plane'/217, l='MpServer', x=119.55, y=64.00, z=262.89], EntityDoeAngora['Angora Doe'/218, l='MpServer', x=122.80, y=67.44, z=317.97], EntityZombie['Zombie'/219, l='MpServer', x=116.17, y=20.00, z=330.51], EntityBat['Bat'/220, l='MpServer', x=112.71, y=22.90, z=327.37], EntityZombie['Zombie'/221, l='MpServer', x=120.23, y=41.00, z=325.46], EntityRoosterLeghorn['Leghorn Rooster'/229, l='MpServer', x=142.30, y=46.00, z=272.70], EntityEweFriesian['Friesian Ewe'/230, l='MpServer', x=143.50, y=63.20, z=285.50], EntityCowFriesian['Friesian Cow'/231, l='MpServer', x=138.98, y=69.00, z=300.00], EntitySpider['Spider'/232, l='MpServer', x=139.50, y=57.00, z=315.50], EntitySkeleton['Skeleton'/233, l='MpServer', x=142.50, y=57.00, z=318.50], EntityBullFriesian['Friesian Bull'/234, l='MpServer', x=125.97, y=70.00, z=311.85], EntityFenceFastener['Fastener'/493, l='MpServer', x=214.50, y=85.50, z=285.50], EntityFenceFastener['Fastener'/494, l='MpServer', x=216.50, y=85.50, z=285.50], EntityFenceFastener['Fastener'/495, l='MpServer', x=210.50, y=94.50, z=284.50], EntityFenceFastener['Fastener'/496, l='MpServer', x=220.50, y=94.50, z=284.50], EntityRabbitDoeDutch['Dutch Doe'/241, l='MpServer', x=151.35, y=65.00, z=240.62], EntityCreeper['Creeper'/242, l='MpServer', x=146.50, y=46.00, z=269.50], EntityFenceFastener['Fastener'/498, l='MpServer', x=214.50, y=85.50, z=288.50], EntitySkeleton['Skeleton'/243, l='MpServer', x=146.50, y=46.00, z=270.50], EntityFenceFastener['Fastener'/499, l='MpServer', x=216.50, y=85.50, z=288.50], EntitySkeleton['Skeleton'/244, l='MpServer', x=144.52, y=45.00, z=269.08], EntityFenceFastener['Fastener'/500, l='MpServer', x=210.50, y=94.50, z=295.50], EntityRamMerino['Merino Ram'/245, l='MpServer', x=152.99, y=64.00, z=268.01], EntityFenceFastener['Fastener'/501, l='MpServer', x=220.50, y=94.50, z=295.50], EntityRoosterLeghorn['Leghorn Rooster'/246, l='MpServer', x=144.48, y=45.00, z=286.41], EntityMoped['Moped'/247, l='MpServer', x=157.52, y=64.00, z=273.56], EntityZombie['Zombie'/121, l='MpServer', x=40.24, y=44.00, z=189.51]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 779211688 bytes (743 MB) / 1509949440 bytes (1440 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID               | Version                  | Source                                    | Signature                                |
	|:------ |:---------------- |:------------------------ |:----------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft        | 1.12.2                   | minecraft.jar                             | None                                     |
	| UCHIJA | mcp              | 9.42                     | minecraft.jar                             | None                                     |
	| UCHIJA | FML              | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge            | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | obfuscate        | 0.2.6                    | minecraft.jar                             | None                                     |
	| UCHIJA | craftstudioapi   | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar     | None                                     |
	| UCHIJA | harvestcraft     | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zb.jar           | None                                     |
	| UCHIJA | animania         | 1.6.2                    | animania-1.12.2-1.6.2.jar                 | None                                     |
	| UCHIJA | bibliocraft      | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar         | None                                     |
	| UCHIJA | chiselsandbits   | 14.29                    | chiselsandbits-14.29.jar                  | None                                     |
	| UCHIJA | cdm              | 0.4.1                    | device-mod-0.4.1-1.12.2.jar               | None                                     |
	| UCHIJA | discordchat      | 2.3.0                    | DiscordChat-1.12.2-2.3.0.jar              | None                                     |
	| UCHIJA | fairylights      | 2.1.5                    | fairylights-2.1.5-1.12.2.jar              | None                                     |
	| UCHIJA | jei              | 4.13.1.225               | jei_1.12.2-4.13.1.225.jar                 | None                                     |
	| UCHIJA | ftblib           | 5.4.0.73                 | FTBLib-5.4.0.73.jar                       | None                                     |
	| UCHIJA | ftbutilities     | 5.3.0.69                 | FTBUtilities-5.3.0.69.jar                 | None                                     |
	| UCHIJA | cfm              | 6.2.0                    | furniture-6.2.0-1.12.2.jar                | None                                     |
	| UCHIJA | gravestone       | 1.10.1                   | gravestone-1.10.1.jar                     | None                                     |
	| UCHIJA | intwheel         | 1.2.7                    | intwheel-1.12-1.2.7.jar                   | None                                     |
	| UCHIJA | inventorytweaks  | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | moreplayermodels | 1.12.2                   | MorePlayerModels_1.12.2(18jan18).jar      | None                                     |
	| UCHIJA | neat             | 1.4-17                   | Neat+1.4-17.jar                           | None                                     |
	| UCHIJA | sereneseasons    | 1.2.15                   | SereneSeasons-1.12.2-1.2.15-universal.jar | None                                     |
	| UCHIJA | tails            | 1.12-1.10.0              | Tails-1.12-1.10.0.jar                     | None                                     |
	| UCHIJA | vehicle          | 0.35.0                   | vehicle-mod-0.35.0-1.12.2.jar             | None                                     |
	| UCHIJA | waystones        | 4.0.67                   | Waystones_1.12.2-4.0.67.jar               | None                                     |
	| UCHIJA | xaerominimap     | 1.15.9                   | Xaeros_Minimap_1.15.9_Forge_1.12.jar      | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.82' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.82, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Annahstas_Beastrinia_1.12_v1.04.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: KUDA-Shaders v6.1 Legacy.zip
	OpenGlVersion: 4.6.0 NVIDIA 398.82
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

This only happens when **allow-flight** is set to true. Disabling this stops the error from occurring again, but makes it impossible to fly vehicles (at least in survival mode), as the server kicks you after flying a short distance.

Note that this only crashes the **client**, not the server.

It is definitely the plane entity causing this. Even spawning a fresh sports plane with allow-flight enabled causes an immediate crash.

**Comment by FujiMakoto** [comment]
Actually, this doesn't seem to be related to allow-flight, it's just.. random.

Restarting the server a few times seems to fix the issue. You just have to keep restarting and hope you get lucky I guess?

This seems to be the exact same issues mentioned in #21 and #60
